export const CHANGE_THEME = 'CHANGE_THEME';
export const THEME_BOX_SHOW = 'THEME_BOX_SHOW';

export const NEWEST_OPINION = 'NEWEST_OPINION';

export const ON_SEARCH_CONTENT = 'ON_SEARCH_CONTENT';

export const GET_USER_INFO = 'GET_USER_INFO';

export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';

// 搜索及筛选舆情请求
export const OPINION_SEARCH_REQUESTED = 'OPINION_SEARCH_REQUESTED';
// 搜索及筛选舆情请求成功
export const OPINION_SEARCH_SUCCEEDED = 'OPINION_SEARCH_SUCCEEDED';

// 同步搜索关键词
export const SEARCH_KEYWORD_SYNC = 'SEARCH_KEYWORD_SYNC';

// 设置预警类型
export const SET_OPINION_TYPE_REQUESTED = 'SET_OPINION_TYPE_REQUESTED';
export const SET_OPINION_TYPE_SUCCEEDED = 'SET_OPINION_TYPE_SUCCEEDED';
//设置路由变化
export const SET_LOCATION_PATHNAME = 'SET_LOCATION_PATHNAME';

// 获取素材库列表
export const GET_MATERIAL_OPINION_LIST_REQUESTED = 'GET_MATERIAL_OPINION_LIST_REQUESTED';
export const GET_MATERIAL_OPINION_LIST_SUCCEEDED = 'GET_MATERIAL_OPINION_LIST_SUCCEEDED';
//获取规则信息
export const GET_TOPIC_ANDRULE_REQUESTED = 'GET_TOPIC_ANDRULE_REQUESTED';
export const GET_TOPIC_ANDRULE_SUCCEEDED = 'GET_TOPIC_ANDRULE_SUCCEEDED';

export const GET_COLLECTION_ANDRULE_REQUESTED = 'GET_COLLECTION_ANDRULE_REQUESTED';
export const GET_COLLECTION_ANDRULE_SUCCEEDED = 'GET_COLLECTION_ANDRULE_SUCCEEDED';

// 获取素材库素材详细信息
export const GET_MATERIAL_OPINION_DETAIL_REQUESTED = 'GET_MATERIAL_OPINION_DETAIL_REQUESTED';
export const GET_MATERIAL_OPINION_DETAIL_SUCCEEDED = 'GET_MATERIAL_OPINION_DETAIL_SUCCEEDED';

// 新增素材库
export const ADD_MATERIAL_OPINION_REQUESTED = 'ADD_MATERIAL_OPINION_REQUESTED';
export const ADD_MATERIAL_OPINION__SUCCEEDED = 'ADD_MATERIAL_OPINION__SUCCEEDED';

// 获取收藏夹列表
export const GET_COLLECTION_OPINION_LIST_REQUESTED = 'GET_COLLECTION_OPINION_LIST_REQUESTED';
export const GET_COLLECTION_OPINION_LIST_SUCCEEDED = 'GET_COLLECTION_OPINION_LIST_SUCCEEDED';
// 获取收藏夹素材详细信息
export const GET_COLLECTION__OPINION_DETAIL_REQUESTED = 'GET_COLLECTION_OPINION_DETAIL_REQUESTED';
export const GET_COLLECTION__OPINION_DETAIL_SUCCEEDED = 'GET_COLLECTION_OPINION_DETAIL_SUCCEEDED';

// 获取报告列表
export const GET_REPORT_LIST_REQUESTED = 'GET_REPORT_LIST_REQUESTED';
export const GET_REPORT_LIST_SUCCEEDED= 'GET_REPORT_LIST_SUCCEEDED';

// 获取报告内容
export const GET_REPORT_DETAIL_REQUESTED = 'GET_REPORT_DETAIL_REQUESTED';
export const GET_REPORT_DETAIL_SUCCEEDED = 'GET_REPORT_DETAIL_SUCCEEDED';

//导出功能跳转
export const EXPORT_SKIP = 'EXPORT_SKIP';

//简报信息
export const REPORT_MESSAGE = 'REPORT_MESSAGE';

// 获取分类舆情内容
export const GET_SORTED_CONTENT_REQUESTED = 'GET_SORTED_CONTENT_REQUESTED';
export const GET_SORTED_CONTENT_SUCCEEDED = 'GET_SORTED_CONTENT_SUCCEEDED';


//获取专题舆情
export const GET_TOPIC_SHOWLIST_REQUESTED = 'GET_TOPIC_SHOWLIST_REQUESTED';
export const GET_TOPIC_SHOWLIST_SUCCEEDED = 'GET_TOPIC_SHOWLIST_SUCCEEDED';

// 分类id切换
export const CHANGE_CLF_ID = 'CHANGE_CLF_ID';

//专题报告导出信息

export const TOPIC_REPORT_EXPORT='TOPIC_REPORT_EXPORT';
//单条录入修改
export const ADD_MESSAGE_REMOVE='ADD_MESSAGE_REMOVE';

// 获取分类的列表项
export const GET_SORTED_MENU_REQUESTED = 'GET_SORTED_MENU_REQUESTED';
export const GET_SORTED_MENU_SUCCEEDED = 'GET_SORTED_MENU_SUCCEEDED';
//专题左侧导航信息
export const TOPIC_NAV_MESSAGE_REQUESTED='TOPIC_NAV_MESSAGE_REQUESTED';
export const TOPIC_NAV_MESSAGE_SUCCEEDED='TOPIC_NAV_MESSAGE_SUCCEEDED';
//上下分页器页码
export const PAGINATION_PAGE='PAGINATION_PAGE';
//首页模块
export const HOME_MODULE='HOME_MODULE';
//筛选栏显示状态
export const SEARCH_STATE='SEARCH_STATE';